# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Listwidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 592)
        self.intensityWidget = QtWidgets.QListWidget(Dialog)
        self.intensityWidget.setGeometry(QtCore.QRect(120, 60, 256, 192))
        self.intensityWidget.setObjectName("intensityWidget")
        item = QtWidgets.QListWidgetItem()
        self.intensityWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.intensityWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.intensityWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.intensityWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.intensityWidget.addItem(item)
        self.emotionWidget = QtWidgets.QListWidget(Dialog)
        self.emotionWidget.setGeometry(QtCore.QRect(490, 60, 256, 192))
        self.emotionWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.emotionWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.emotionWidget.setSelectionRectVisible(False)
        self.emotionWidget.setObjectName("emotionWidget")
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emotionWidget.addItem(item)
        self.resultWidget = QtWidgets.QListWidget(Dialog)
        self.resultWidget.setGeometry(QtCore.QRect(290, 320, 256, 192))
        self.resultWidget.setObjectName("resultWidget")
        self.labelIntensity = QtWidgets.QLabel(Dialog)
        self.labelIntensity.setGeometry(QtCore.QRect(10, 60, 101, 41))
        self.labelIntensity.setObjectName("labelIntensity")
        self.labelEmotions = QtWidgets.QLabel(Dialog)
        self.labelEmotions.setGeometry(QtCore.QRect(390, 60, 101, 41))
        self.labelEmotions.setObjectName("labelEmotions")
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setGeometry(QtCore.QRect(60, 330, 211, 51))
        self.labelResult.setObjectName("labelResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.intensityWidget.isSortingEnabled()
        self.intensityWidget.setSortingEnabled(False)
        item = self.intensityWidget.item(0)
        item.setText(_translate("Dialog", "Very Weak"))
        item = self.intensityWidget.item(1)
        item.setText(_translate("Dialog", "Weak"))
        item = self.intensityWidget.item(2)
        item.setText(_translate("Dialog", "Medium"))
        item = self.intensityWidget.item(3)
        item.setText(_translate("Dialog", "Strong"))
        item = self.intensityWidget.item(4)
        item.setText(_translate("Dialog", "Very Strong"))
        self.intensityWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.emotionWidget.isSortingEnabled()
        self.emotionWidget.setSortingEnabled(False)
        item = self.emotionWidget.item(0)
        item.setText(_translate("Dialog", "Happy"))
        item = self.emotionWidget.item(1)
        item.setText(_translate("Dialog", "Neutral"))
        item = self.emotionWidget.item(2)
        item.setText(_translate("Dialog", "Surprise"))
        item = self.emotionWidget.item(3)
        item.setText(_translate("Dialog", "Fear"))
        item = self.emotionWidget.item(4)
        item.setText(_translate("Dialog", "Disgust"))
        item = self.emotionWidget.item(5)
        item.setText(_translate("Dialog", "Anger"))
        item = self.emotionWidget.item(6)
        item.setText(_translate("Dialog", "Sad"))
        self.emotionWidget.setSortingEnabled(__sortingEnabled)
        self.labelIntensity.setText(_translate("Dialog", "Choose intensity:"))
        self.labelEmotions.setText(_translate("Dialog", "Choose emotions:"))
        self.labelResult.setText(_translate("Dialog", "The resulting intensities and emotions are:"))

